using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.EntityFrameworkCore;
using SecurityScanDashboard.Data;
using SecurityScanDashboard.Models;

namespace SecurityScanDashboard.Services
{
    public interface IAuthenticationService
    {
        Task<(bool Success, string Message, User? User)> RegisterAsync(string username, string email, string password, string firstName, string lastName);
        Task<(bool Success, string Message, User? User)> LoginAsync(HttpContext httpContext, string username, string password, bool rememberMe);
        Task LogoutAsync(HttpContext httpContext);
        Task<User?> GetCurrentUserAsync(ClaimsPrincipal claimsPrincipal);
        Task<bool> IsInRoleAsync(int userId, string roleName);
        string HashPassword(string password);
        bool VerifyPassword(string password, string passwordHash);
    }

    public class AuthenticationService : IAuthenticationService
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<AuthenticationService> _logger;

        public AuthenticationService(ApplicationDbContext context, ILogger<AuthenticationService> logger)
        {
            _context = context;
            _logger = logger;
        }

        public async Task<(bool Success, string Message, User? User)> RegisterAsync(
            string username, string email, string password, string firstName, string lastName)
        {
            try
            {
                // Check if username exists
                if (await _context.Users.AnyAsync(u => u.Username == username))
                {
                    return (false, "Bu kullanıcı adı zaten kullanılıyor.", null);
                }

                // Check if email exists
                if (await _context.Users.AnyAsync(u => u.Email == email))
                {
                    return (false, "Bu e-posta adresi zaten kullanılıyor.", null);
                }

                // Get our user_id from user_schemas (required by RLS policy for created_by)
                var createdBy = await _context.Database
                    .SqlQueryRaw<int>("SELECT user_id AS \"Value\" FROM public.user_schemas WHERE schema_name = current_user")
                    .FirstOrDefaultAsync();

                // Create new user - id is auto-generated by DB (GENERATED ALWAYS AS IDENTITY)
                var user = new User
                {
                    Username = username,
                    Email = email,
                    PasswordHash = HashPassword(password),
                    FirstName = firstName,
                    LastName = lastName,
                    UserType = "Student",
                    CreatedBy = createdBy,
                    CreateDate = DateTime.UtcNow,
                    UpdateDate = DateTime.UtcNow,
                    LanguageCode = "tr"
                };

                _context.Users.Add(user);
                await _context.SaveChangesAsync();

                _logger.LogInformation("New user registered: {Username} ({Email})", username, email);

                return (true, "Kayıt başarılı!", user);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error during user registration");
                return (false, "Kayıt sırasında bir hata oluştu.", null);
            }
        }

        public async Task<(bool Success, string Message, User? User)> LoginAsync(
            HttpContext httpContext, string username, string password, bool rememberMe)
        {
            try
            {
                // Find user by username or email
                var user = await _context.Users
                    .Include(u => u.UserRoles)
                    .ThenInclude(ur => ur.Role)
                    .FirstOrDefaultAsync(u => u.Username == username || u.Email == username);

                if (user == null)
                {
                    return (false, "Kullanıcı adı veya şifre hatalı.", null);
                }

                // Verify password
                if (!VerifyPassword(password, user.PasswordHash))
                {
                    return (false, "Kullanıcı adı veya şifre hatalı.", null);
                }

                // Create claims
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.NameIdentifier, user.Id.ToString()),
                    new Claim(ClaimTypes.Name, user.Username),
                    new Claim(ClaimTypes.Email, user.Email),
                    new Claim("FullName", user.FullName)
                };

                // Add role claims
                foreach (var userRole in user.UserRoles)
                {
                    if (userRole.Role.IsActive)
                    {
                        claims.Add(new Claim(ClaimTypes.Role, userRole.Role.Name));
                    }
                }

                var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                var authProperties = new AuthenticationProperties
                {
                    IsPersistent = rememberMe,
                    ExpiresUtc = rememberMe ? DateTimeOffset.UtcNow.AddDays(30) : DateTimeOffset.UtcNow.AddHours(8)
                };

                await httpContext.SignInAsync(
                    CookieAuthenticationDefaults.AuthenticationScheme,
                    new ClaimsPrincipal(claimsIdentity),
                    authProperties);

                _logger.LogInformation("User logged in: {Username}", username);

                return (true, "Giriş başarılı!", user);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error during user login");
                return (false, "Giriş sırasında bir hata oluştu.", null);
            }
        }

        public async Task LogoutAsync(HttpContext httpContext)
        {
            await httpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            _logger.LogInformation("User logged out");
        }

        public async Task<User?> GetCurrentUserAsync(ClaimsPrincipal claimsPrincipal)
        {
            var userIdClaim = claimsPrincipal.FindFirst(ClaimTypes.NameIdentifier);
            if (userIdClaim == null || !int.TryParse(userIdClaim.Value, out int userId))
            {
                return null;
            }

            return await _context.Users
                .Include(u => u.UserRoles)
                .ThenInclude(ur => ur.Role)
                .FirstOrDefaultAsync(u => u.Id == userId);
        }

        public async Task<bool> IsInRoleAsync(int userId, string roleName)
        {
            return await _context.UserRoles
                .Include(ur => ur.Role)
                .AnyAsync(ur => ur.UserId == userId && ur.Role.Name == roleName && ur.Role.IsActive);
        }

        public string HashPassword(string password)
        {
            // Use SHA256 for hashing (matching school's system)
            using var sha256 = SHA256.Create();
            var hashedBytes = sha256.ComputeHash(Encoding.UTF8.GetBytes(password));
            return Convert.ToBase64String(hashedBytes);
        }

        public bool VerifyPassword(string password, string passwordHash)
        {
            var hashedInput = HashPassword(password);
            return hashedInput == passwordHash;
        }
    }
}
